apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/pvc.yaml
  - resources/service.yaml
  - resources/namespace.yaml
  - resources/hpa.yaml
  - resources/poddisruptionbudget.yaml

commonLabels:
  project: yabetsu-project
  type: grafana

namespace: grafana-qa

configMapGenerator:
- name: grafana-config
  files:
    - resources/configmaps.yaml