apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: grafana-hpa
  labels:
    app: grafana
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grafana
  minReplicas: 2
  maxReplicas: 10
