apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-claim
  labels:
    app: grafana
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
