apiVersion: autoscaling.k8s.io/v2beta2
kind: VerticalPodAutoscaler
metadata:
  name: grafana-vpa
  labels:
    app: grafana
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: grafana