apiVersion: apps/v1
kind: Deployment
metadata:
  name:  yabetsu-grafana
  labels:
    name:  yabetsu-grafana
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate